CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS GRAPH;
CREATE SCHEMA IF NOT EXISTS APP;

-- 1. PAPERS: basic metadata for the academic documents
CREATE OR REPLACE TABLE RAW.PAPERS (
    PAPER_ID VARCHAR,
    TITLE VARCHAR,
    AUTHORS VARCHAR,
    ABSTRACT STRING,
    PUBLICATION_YEAR INT,
    SOURCE_URL VARCHAR,
    PRIMARY KEY (PAPER_ID)
);

-- 2. CHUNKS: the text segments for Vector RAG, with Snowflake VECTOR data type support
CREATE OR REPLACE TABLE RAW.CHUNKS (
    CHUNK_ID VARCHAR,
    PAPER_ID VARCHAR,
    CHUNK_INDEX INT,
    TEXT_CONTENT STRING,
    EMBEDDING VECTOR(FLOAT, 768), -- Default dimensionality assuming e.g. an OpenAI or HF model
    PRIMARY KEY (CHUNK_ID),
    FOREIGN KEY (PAPER_ID) REFERENCES RAW.PAPERS(PAPER_ID)
);

-- 3. FIGURES: Metadata for figures extracted from papers
CREATE OR REPLACE TABLE RAW.FIGURES (
    FIGURE_ID VARCHAR,
    PAPER_ID VARCHAR,
    PAGE_NUMBER INT,
    CAPTION STRING,
    IMAGE_PATH VARCHAR,
    PRIMARY KEY (FIGURE_ID),
    FOREIGN KEY (PAPER_ID) REFERENCES RAW.PAPERS(PAPER_ID)
);

-- 4. KNOWLEDGE_NODES: Entities extracted for the knowledge graph
CREATE OR REPLACE TABLE GRAPH.KNOWLEDGE_NODES (
    NODE_ID VARCHAR,
    LABEL VARCHAR,      -- e.g., 'Concept', 'Method', 'Dataset', 'Task'
    NAME VARCHAR,       -- e.g., 'Retrieval-Augmented Generation'
    EMBEDDING VECTOR(FLOAT, 768), 
    PRIMARY KEY (NODE_ID)
);

-- 5. KNOWLEDGE_EDGES: Relationships between entities
CREATE OR REPLACE TABLE GRAPH.KNOWLEDGE_EDGES (
    EDGE_ID VARCHAR,
    SOURCE_NODE_ID VARCHAR,
    TARGET_NODE_ID VARCHAR,
    RELATION_TYPE VARCHAR, -- e.g., 'USES', 'IMPROVES', 'EVALUATED_ON'
    WEIGHT FLOAT,
    PRIMARY KEY (EDGE_ID),
    FOREIGN KEY (SOURCE_NODE_ID) REFERENCES GRAPH.KNOWLEDGE_NODES(NODE_ID),
    FOREIGN KEY (TARGET_NODE_ID) REFERENCES GRAPH.KNOWLEDGE_NODES(NODE_ID)
);

-- 6. METRICS: Track evaluation scores and logging for generated answers
CREATE OR REPLACE TABLE APP.EVAL_METRICS (
    LOG_ID VARCHAR,
    QUESTION STRING,
    GENERATED_RESPONSE STRING,
    CONTEXT_USED STRING,
    FAITHFULNESS_SCORE FLOAT,
    ANSWER_RELEVANCE_SCORE FLOAT,
    CONFIDENCE FLOAT,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LOG_ID)
);
